export const KAS_API  = "https://api.kaspa.org";
export const EXPLORER = "https://explorer.kaspa.org";
export const TREASURY = "kaspa:qpv7fcvdlz6th4hqjtm9qkkms2dw0raem963x3hm8glu3kjgj7922vy69hv85";
export const FEE_RATE = 0.20;           // KAS per execution cycle
export const TREASURY_SPLIT = 0.30;     // 30% of fees → treasury
export const AGENT_SPLIT    = 0.70;     // 70% of fees → agent pool
export const RESERVE  = 0.50;
export const NET_FEE  = 0.0002;
export const CONF_THRESHOLD = 0.75;
